name: youtap_movie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shimmer: 2.0.0
  intl: 0.17.0
  dio: 4.0.6
  google_fonts: 2.2.0
  sizer: 2.0.15
  flutter_svg: 1.0.3
  carousel_slider: 4.1.1
  cached_network_image: 3.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/svg/
  uses-material-design: true

